# version: "3"
# services:
#   app:
#     image: sistema-estudiantes:2.0.0
#     volumes:
#       - ./:/app/
#       - /app/node_modules # <-- en caso de que no exista esta carpeta la tengamos en el proyecto y hacer le mapeo del volumen
#     container_name: SISTEMA_ESTUDIANTES
#     ports:
#       - ${PORT}:${PORT}
#     environment:
#       - APP_VERSION=${APP_VERSION}
#       - MONGODB=${MONGODB}
#       - MONGODB_DATABASE=${MONGODB_DATABASE}
#       - JWT_SECRET=${JWT_SECRET}
# volumes:
#   sistema_estudiante:
#     external: false
version: "3"
services:
  db:
    container_name: BD_SISTEMA_ESTUDIANTES
    restart: always # Reiniciar el contenedor si se detiene
    image: mongo:5.0
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
volumes:
  reserva_club:
    external: true
   